### ISSUE TITLE
Browser too old (WP theme)

### ISSUE THREAD

**Issue by luisherranz** [frontity/wordcamp-theme#34]
This is for the WP theme. We need a page to show something when the browser is too old for the PWA technology.

Something like this:
![artboard](https://user-images.githubusercontent.com/3305402/40482300-e57df1be-5f43-11e8-9c6d-2ced3cd13233.jpg)

**Comment by lucijanblagonic** [comment]
![desktop not supported](https://user-images.githubusercontent.com/773721/40726543-3e9bc5a0-6426-11e8-832a-36a1e5dc1963.png)

Added the desktop styles. I would just use the plain background and fonts so that app is always in focus (even if it's not loaded). Uploading Sketch files. Modified the texts a little bit. Would be great if we could mention what browsers are supported in the text (I'm not sure which ones have full support).

**Comment by luisherranz** [comment]
> Would be great if we could mention what browsers are supported in the text (I'm not sure which ones have full support).

Chrome 40+ and Safari 9.0+

@lucijanblagonic most likely this will be shown on old mobile devices. Should we hide the device frame in mobile (responsive) or should we place it below the text?

**Comment by lucijanblagonic** [comment]
Good idea, let's hide the device frame as there is nothing worthy of showing (on desktop is mostly for consistency between layouts).

**Comment by DAreRodz** [comment]
Closed at https://github.com/frontity/wordcamp-wp-theme/commit/b0852b785126f4a272177d11b86876e547428641.
