### ISSUE TITLE
'My schedule' page

### ISSUE THREAD

**Issue by ePascalC** [frontity/wordcamp-theme#51]
Create a page that lists all sessions that were set as favorite in the different tracks. This would create a kind of 'My personal schedule' page. It would need to show also the breaks and the meeting room (maybe in different colors so I know when I need to change meeting room?

**Comment by luisherranz** [comment]
Awesome. I'll tag it as `nice-to-have` and for the `design-team` first. Once the design it's done, please remove the design-team tag and add ours (dev-team).

**Comment by lucijanblagonic** [comment]
I would perhaps use "Favourites" in the menu so that the Schedule isn't repeated twice (Schedule My Schedule).

![my schedule](https://user-images.githubusercontent.com/773721/40999916-a706a61a-690c-11e8-91bb-153b5dc9dec9.png)

![menu](https://user-images.githubusercontent.com/773721/40999952-be924244-690c-11e8-9890-fcab2b03a3bf.png)

Thoughts? @ePascalC @luisherranz

**Comment by mburridge** [comment]
Or how about calling it "My WCEU"?

**Comment by lucijanblagonic** [comment]
My WCEU is too vague imho. Better to call it My favorites if you think favorites isn't good enough.
