### ISSUE TITLE
Content: instructions for app use

### ISSUE THREAD

**Issue by jennybeaumont** [frontity/wordcamp-theme#54]
@mburridge has indicated

> Might be worth adding some simple instructions for use. I think Android prompts the user to install the app to the home screen (not sure, I'm not an Android user) but iOS makes you jump through a couple of hoops I think.
> 
> It's also worth adding that only very recent versions of iOS support PWA technologies.

Please provide us with a complete text to be included in our blog announcement. thnx!

**Comment by rmartinezduque** [comment]
Hi @jennybeaumont, this task is for us, right?

**Comment by ePascalC** [comment]
@rmartinezduque Yes please. If you could provide indications on how we could announce the app, that would be perfect. The above quote was for a standard app, but if you know of any limitations/strange behaviour in Android or iOS (in one or the other version) or if you have minimum requirements (like Android or iOS version) please let us know. Of course any other text on how to promote the app is also welcome.
Thanks.

**Comment by jennybeaumont** [comment]
If I could get this by today end of day, that would be much appreciated!

**Comment by luisherranz** [comment]
I'll tag this for us (dev-team). @rmartinezduque could please take care of it?

**Comment by rmartinezduque** [comment]
Sure, I'll work on this today :)

**Comment by jennybeaumont** [comment]
Any progress? :)

**Comment by rmartinezduque** [comment]
Hi @jennybeaumont and @ePascalC. Here you have some instructions for use and other information you can use to announce the app if you wish. Hope it helps. Let me know if you need anything else.

## What is WordCamp Europe’s Progressive Web App?

The WordCamp Europe’s Progressive Web App (PWA from now on) is an app-like mobile web (https://app.wp-europe.org/) that can be accessed instantly from a mobile browser. It delivers the same native experience than a mobile app without the hassle of installing it, just using the web (a URL).

The PWA provides practical information about WordCamp Europe 2018. More specifically, it contains:

- Schedules (On now, up next and full schedule with all sessions ordered by tracks)
- Information on sessions (including time and location)
- Information on speakers
- Venue maps
- Announcements
- Lunch menus
- Code of conduct
- Other useful information about Contributor Day, After Party, etc.

## Minimum requirements

- Android: Chrome 40+ or above
- iOS: Safari 9.0 or above

## Features:

- **Instant loading**: the PWA is designed to load nearly instantly and reliably, even if attendees are under uncertain network conditions.

- **Security**: this PWA is served over HTTPS, a secure connection that protects sensitive information. This way the user and the session do not get exposed to attacks and vulnerabilities.

- **Favorites**: the attendees can use the Favorites feature to add stars to all talks of their interest or the ones that they plan to attend (look out for the ⭐ icon). Marked talks will automatically appear under the “Only favorites” option in Full schedule.

- **Push notifications**: these are instant messages that pop up on the attendee’s device (if he/she has explicitly opted in to receive them). They are sent with the sole objective of keeping attendees notified of updates and important notices. This feature **is not available** on **iOS**.

- **Offline support**: this PWA is aimed to be reliable if the network fails. This means that if attendees temporarily lose their connection, they will not be interrupted while using the app and will continue accessing the site offline. They may not see the newest data but a stored version instead. On **iOS**, this feature is only available for **11.3 version** or above.

- **Add to Home Screen**: when attendees visit the PWA, they will have the choice to add it to their home screen. This feature helps them save the PWA for instant access and start using it regularly without running out of device space. If no “Add to home screen” popup shows up, attendees can refer to the instructions below to add the PWA to their home screen.

## Instructions for app use

The PWA can be directly opened by accessing the page URL https://app.wp-europe.org/ on a mobile browser, just like any other mobile website.

In order to add the PWA to the home screen, please follow these instructions:

**Android (Chrome)**

Step 1. Open website (app.wp-europe.org) in Chrome for Android and tap the Menu button.

Step 2. Tap `Add to Home Screen` option

Step 3. Rename the button (optional) and tap `Add`

**iOS (Safari)**

Step 1. Open website (app.wp-europe.org) in Safari and tap the Action button.

Step 2. Tap `Add to Home Screen` button

Step 3. Rename the button (optional) and tap `Add` or `Done`

You can find the "Add to home screen" screenshots [here](https://drive.google.com/drive/folders/1c7tKeA5T_PlMYLi827wabPIoAxVN7kt9?usp=sharing
).

**Comment by jennybeaumont** [comment]
This is amazing, thank you! (going to leave this open until tomorrow when we finalize the post, cheers!)

**Comment by luisherranz** [comment]
@jennybeaumont please note that **Offline support** is not ready yet but I'll work on it next week to make sure it is available before the event. The rest of the features are already in place.

**Comment by jennybeaumont** [comment]
I got everything I needed here - will refer back for the attendee email going out June 11, but have copied the link so closing this out! :)

**Comment by rmartinezduque** [comment]
This is the updated text of the Push Notifications:

- **Push notifications**: these are instant messages that pop up on the attendee’s device (if he/she has explicitly opted in to receive them). They are sent with the sole objective of keeping attendees notified of updates and important notices. This feature **is not available** on **iOS**.
