### ISSUE TITLE
Schedules general title and tab labels

### ISSUE THREAD

**Issue by mburridge** [frontity/wordcamp-theme#60]
The bottom nav bar, i.e. the 'On now', 'Up next', and 'Full Schedule' buttons, should be visible at all times. Whatever page the user is on they should with just one tap be able to go to any of the above.

Also please change 'Full' to 'Full Schedule'.

**Comment by ePascalC** [comment]
@mburridge I would go for 'Schedule'. If you put 'Full Schedule' it might be too long and go on the next line.

**Comment by luisherranz** [comment]
Yes, I guess @lucijanblagonic chose `Full` in the design because it's short for the Tab and decided to put `Schedule` on the top. So this is related to https://github.com/frontity/wordcamp-theme/issues/56. Hopefully he can chime in.

For now I'll tag it as blocked until a decision is made.

**Comment by luisherranz** [comment]
Please take a decision about:
 - [ ] PWA Title (now it is `Schedule`)
 - [ ] Full Schedule Tab (now it is `Full`)

**Comment by lucijanblagonic** [comment]
I disagree. This is a progressive web app, but it's still an web app. Emulating tab bars always visible tab bars would make sense if all the pages were visible in that tab bar. They are not, we don't have announcements or event map.

Tab bar in our case serves for that specific schedule context and nothing more. Yes, schedule is. the most important thing, and that's why it's the first thing you see when you open the app. I'm OK with changing the title to WCEU Schedule (to make things more obvious) but I wouldn't change the tab names as those are made to fit with even the smallest ones 320px width devices.

**Comment by ePascalC** [comment]
@luisherranz Decision: Leave it like it is and let's review it in a next version of the app.
